### ISSUE TITLE
bug: 'import {} from '/u/xxx/xxx.ts' not work in flow script editor

### ISSUE THREAD

**Issue by ImSingee** [windmill-labs/windmill#2378] opened 2023-10-03 15:40 UTC
### Describe the bug

In the script editor of a flow script, the `import {} from '/u/xxx/xxx.ts'` (https://www.windmill.dev/docs/advanced/sharing_common_logic#deno-or-bun-relative-imports-for-sharing-common-logic) cannot be highlight well in the editor.

### To reproduce

1. Create a new flow
2. Create a new 'typescript (deno)' script step inside flow
3. Write `import {} from '/u/xxx/xxx.ts'`, it will be error in the editor

### Expected behavior

There shouldn't be any error in editor

### Screenshots

<img width="690" alt="image" src="https://github.com/windmill-labs/windmill/assets/11208082/a096061f-deb8-4ca2-8699-d3f949938057">

### Additional Context

The check condition failed at https://github.com/windmill-labs/windmill/blob/ab2ba72f04e8b5876514832adadad980f8600d29/frontend/src/lib/components/Editor.svelte#L633

the `filePath` variable does not contain any '/'

**Comment by rubenfiszel** [comment] 2023-10-07 14:37
fixed on latest

**Closed by rubenfiszel** 2023-10-07 14:37 UTC
Labels: bug

**Comment by jsbrain** [comment] 2024-02-03 16:51
This seems like it's not working anymore. Relative imports work, trying to import from `/u/username/script.bun.ts` or `/f/foldername/script.bun.ts` does not work for me.

**Comment by jsbrain** [comment] 2024-02-03 16:53
Also, importing from inline scripts in flow, none of the methods work, not even local. Not sure if this is by design though?

**Comment by rubenfiszel** [comment] 2024-02-03 17:11
@jsbrain 

.bun.ts is something that only the CLI is aware of. As far as windmill is concerned, regardless of if it's deno or bun, you would use x.ts and not x.bun.ts

Also do note that errors you see in the editors have nothing to do with the ability of windmill to resolve the imports at runtime, it merely indicate that our plugin for monaco was not able to resolve the imports.

In the latest version of the CLI, we introduced `defaultTs` to avoid having to use .bun.ts if the primary language used is bun: https://github.com/windmill-labs/windmill-sync-example/blob/main/wmill.yaml#L2

**Comment by jsbrain** [comment] 2024-02-03 17:36
@rubenfiszel thanks for the quick reply.

I should have been a little more specific I guess.

The imports per se work, but I'm trying to share types between multiple inline scripts so I don't have to copy pasta everything. This doesn't seem to work with inline scripts.

I managed to get it to work now by using normal scripts and referencing them in the flow which is a feasible solution for my case, just wondering wether this might be by design or why it's not working as stated in the docs.

I haven't had any success with the absolute imports though, no combination of bun/deno/rest seems to work for me (running on 1.260.1)
